### ISSUE TITLE
Jellyfin integration

### ISSUE THREAD

**Issue by FuzzyGrim** [FuzzyGrim/Yamtrack#130]
A jellyfin integration via webhooks/plugin is planned so that episodes can be added automatically.

**Comment by DragonHeart69** [comment]
can you also add plex to the routmap?

**Comment by FuzzyGrim** [comment]
I will consider it after adding Jellyfin integration, but I don't know how feasible it would be as I'm not a Plex user.

**Comment by Radieserlbrot** [comment]
Do you have any news about the integration of Jellyfin? I am searching for a solution that is compatible with Jellyfin... Thx

**Comment by FuzzyGrim** [comment]
Still on the roadmap, I'll probably do #144 > #157 and then this
