### ISSUE TITLE
Feature: upcoming show episodes overview

### ISSUE THREAD

**Issue by GarryG** [FuzzyGrim/Yamtrack#134]
Having a page that gives you an overview of all of your shows' upcoming episodes would be nice. I currently use Episoder, and get an output like this:

❯ episoder list -n6
Fri, Mar 29, 2024 Penn & Teller: Fool Us 10x17
Sun, Mar 31, 2024 The Walking Dead: The Ones Who Live 1x06
Sun, Mar 31, 2024 Last Week Tonight with John Oliver 11x06
[..]
Thu, Apr 04, 2024 Young Sheldon 7x06
Thu, Apr 04, 2024 Invincible (2021) 2x08

Or, something like the Recent/Upcoming overview in the Android app SeriesGuide ...

**Comment by FuzzyGrim** [comment]
Sounds good, I may integrate it into the home page with the media that are in progress.

**Comment by FuzzyGrim** [comment]
Hey! In the new release [0.13.0](https://github.com/FuzzyGrim/Yamtrack/releases/tag/v0.13.0), I have added a calendar view that shows all upcoming media.

![Screenshot 2024-08-23 at 00-02-02 Calendar - Yamtrack](https://github.com/user-attachments/assets/3c00ce8b-9885-4271-a714-0c75f34694e8)
