### ISSUE TITLE
Feature: Functionality to track and display replays

### ISSUE THREAD

**Issue by Appoxo** [FuzzyGrim/Yamtrack#139]
Track and show how often an episode has been watched

Example from trakt
![grafik](https://github.com/FuzzyGrim/Yamtrack/assets/17850993/b71f0ab7-126e-4b66-86d6-53b0a974d0de)

Nice to have would be the option to reset the progress-bar to not loose track of the progress when re-watching a show

**Comment by FuzzyGrim** [comment]
Thanks for the suggestion, it should be easy to add a field for episode rewatches.
