### ISSUE TITLE
[Feature Request] English titles for anime/manga

### ISSUE THREAD

**Issue by reitenth** [FuzzyGrim/Yamtrack#150]
could there be an option to use english titles for animanga? thanks!

**Comment by FuzzyGrim** [comment]
I'm currently using MyAnimeList for metadata and they don't support English titles. I considered using AniList as they support alternative languages, but it is against their ToS to use their API for competing applications (media trackers).

**Comment by reitenth** [comment]
if u are familiar with ryot, how do they get english names if you dont mind?

**Comment by FuzzyGrim** [comment]
It seems that they use the AniList API.
