### ISSUE TITLE
Feature: Ability to add movies or series of your own.

### ISSUE THREAD

**Issue by 101br03k** [FuzzyGrim/Yamtrack#157]
I am dutch so there are a couple of movies and or series I would like to add to Yamtrack, is it posible to add a feature to add movies because don't show up in the search results?

p.s. this does'nt have any urgency, currently using the excel I used before I discoverd this amazing tool.

**Comment by FuzzyGrim** [comment]
Yes, sounds like a good feature to add. 

But it may be a bug in the app's search, can you find your media on [TMDB](https://www.themoviedb.org)?

**Comment by 101br03k** [comment]
Don't worry it is nog a bug in the search function, I also can not find it on TMDB but that isn't weird sinds its a only dutch spoken movie.

**Comment by Kazer67** [comment]
I agree that a manual add feature for all category would be nice, not only for movies or series but for example for niche manga as well where we fill all that's needed manually.

**Comment by FuzzyGrim** [comment]
Completed in the latest release
