### ISSUE TITLE
Feature: Track Comic Books

### ISSUE THREAD

**Issue by Karsten-Yan** [FuzzyGrim/Yamtrack#180]
Firstly: Great work you are doing here, this is exactly what I was looking for.

Now for my question/feature suggestion:
Would it be possible to add a comic section to track reading status similar to the manga section? The information could be retrieved via the comicvine API. You just have to create an account there to get an API key, which is a bit limited, but should be enough for this purpose, I think. 

One idea could be to have the collected volumes entry as the main entry (e.g.: https://comicvine.gamespot.com/the-walking-dead/4050-30345/) and the individual issues as progress.

Anyway, thanks again for your work :).

**Comment by FuzzyGrim** [comment]
Thank you for your the suggestion and kind words!

I will add this as a planned feature for a future release.

**Comment by Karsten-Yan** [comment]
@FuzzyGrim I just wanted to come to you on this. Since you added book tracking via open library in the last update, I thought it might work for my use case of tracking comic books. And I can confirm that it works so far, I just have to find the corresponding ISBN number and search with that and then I have been able to find everything so far.

I just noticed that some metadata is very incomplete (synopsis, cover art) for most comic books. I created an account at open library and added them to some of my books, how long does it take for those additions to yamtrack? Or is that more on the Open Library side, maybe it just takes some time for the changes to fully propagate everywhere?

Anyway, thanks for all the hard work. This was a very welcome addition!

**Comment by FuzzyGrim** [comment]
Thanks for letting me know. If it works with Open Library then I will close this issue. I'm not a comic reader, so if you find that openlibrary is quite limited for comics, you can reopen the issue and I'll look into Comic Vine.

Yamtrack caches external api requests for 5 hours, so if that time has passed and you don't see updated metadata then it's probably on the Open Library side.

**Comment by UnopposedForce91** [comment]
I find openlibrary extremely lacking in terms of metadata, no description or cover art on lots of comics, comicvine would be the best option. Also I'd like to see comics in a separate category, related: #314

**Comment by FuzzyGrim** [comment]
Added in [v0.22.0](https://github.com/FuzzyGrim/Yamtrack/releases/tag/v0.22.0).

**Comment by UnopposedForce91** [comment]
I actually noticed the change in the demo before the release of v0.22.0, seems like the site is on a nightly build!
Just wanted to say thank you for your responsiveness, I'm immensely grateful.
