### ISSUE TITLE
table view, have a max title length

### ISSUE THREAD

**Issue by reitenth** [FuzzyGrim/Yamtrack#188]
![image](https://github.com/FuzzyGrim/Yamtrack/assets/94771708/9605b4d2-d55f-4804-9e16-78f42666657e)

right now a few of my titles go so long as to cut off the complete, and edit functions on the right. if there was a max title length it would solve this. thanks

**Comment by reitenth** [comment]
kind of to go along witht that, maybe smaller font, or a max line length to keep all entries uniform looking in grid view? thanks.

![image](https://github.com/FuzzyGrim/Yamtrack/assets/94771708/9c99c3ac-b1fa-44d8-9a9e-6339b18e3619)

**Comment by FuzzyGrim** [comment]
There is already a maximum title length for the table view, there seems to be some kind of loading error, can you give me some details on what client you are using? It should look like this on small screens:

![Screenshot 2024-07-08 at 22-27-43 Animes - Yamtrack](https://github.com/FuzzyGrim/Yamtrack/assets/34800654/230922f9-3dea-41a7-b899-90d0f0b2035d)

For the grid view, which was inspired of AniList's layout, I like to be able to read the titles to differentiate the seasons and therefore I am allowing up to a maximum of 2 lines. It would take a really small font for the titles to fit on 1 line consistently.

**Comment by reitenth** [comment]
i'm running docker version dev tag on a 27" 1440p monitor. seems like in the console this is causing it. 
`.text-truncate white-space: nowrap;`

**Comment by FuzzyGrim** [comment]
I have the same setup and I can't reproduce it. I'm not finding those css parameters that could cause it, if possible, can you indicate which css class has those parameters?

Also, has it always been like that, do you see the same styling in my demo instance at [https://yamtrack.fuzzygrim.com/](https://yamtrack.fuzzygrim.com/) with `demo` and `demo` credentials?

**Comment by FuzzyGrim** [comment]
I'm closing it due to inactivity, feel free to reopen it if the problem persists.
