### ISSUE TITLE
Feature Request: Kitsu

### ISSUE THREAD

**Issue by Cwavs** [FuzzyGrim/Yamtrack#204]
The ability to import from Kitsu (https://kitsu.app/) to go along with MAL and AniList would be nice! I'm not sure if this has been mentioned either, and I don't think it's worth a separate issue, but the correct plural of anime is anime, not animes!

**Comment by FuzzyGrim** [comment]
Sounds good, as I haven't used Kitsu before so, I'd appreciate if you could share your Kitsu username or send it to me at github@fuzzygrim.com to more effectively find edge cases

Also, thanks for the mention about the plural thing, I pushed a fix to the dev branch and it will be merged in the next release :)

**Comment by Cwavs** [comment]
Sure, my username is Cwavs so feel free to test it with my account! They do maintain mappings of their entries onto other sites like MAL or AniList.

Glad to hear it :) It was minor issue but it was bugging me because I'm a pedant.

**Comment by FuzzyGrim** [comment]
Hey!

I've been working on importing from Kitsu and it's mostly done. I am using MAL for my app as it is against the terms of use of AniList API to use it for tracking applications and theres a considerable amount of media in your Kitsu account that doesn't have mappings to MAL like some western anime like Gravity Falls or RWBY and some Manhua/Manwha as MAL is quite slow on those.

The feature will be released in the next version of Yamtrack.

**Comment by Cwavs** [comment]
Hi! That's great news! Thanks for the work, I can't wait to test it.

Yeah I figured that might prove an issue. Just so I can gather the effect of the issue, does that mean those series that aren't in MAL cannot currently be imported? Not that I was expecting them all to be of course. Some of them I don't mind searching for and adding manually.

I look forward to trying it out in the next release.
