### ISSUE TITLE
[Feature] [Manga/Manhwa/Manhua] Add MangaUpdates as a source for the search field.

### ISSUE THREAD

**Issue by Kazer67** [FuzzyGrim/Yamtrack#212]
There's a lot of Manga/Manhwa/Manhua that aren't found on Yamtrack, adding MangaUpdates in the search field would unlock a lot of them to be then added.

It's also impossible currently to add manually entry to track them (suggestion in this issue for Movie / Series but would apply for the other category as well: https://github.com/FuzzyGrim/Yamtrack/issues/157)

I'm currently switching to Yamtrack since [MyMangaDataBase](https://github.com/EdwinRodger/MyMangaDataBase) has been archived but the way it worked for MMDB is that you would add manually an entry for a given Manga/hwa/hua and then click a button to fetch data from MangaUpdates to fill the entry.

So a similar feature would allow more tracking (currently I'm using both YamTrack and MMDB in parallel but the goal is to fully switch to only YamTrack since it's an awesome piece of software).

**Comment by FuzzyGrim** [comment]
Completed with https://github.com/FuzzyGrim/Yamtrack/commit/75e496ae893cbca5733258d64d7aba0dc25ac2a5, will be released with the next major release
