### ISSUE TITLE
500 oops when clicking tab after importing

### ISSUE THREAD

**Issue by reitenth** [FuzzyGrim/Yamtrack#218]
im on dev, when i import from anilist i cant click any tabs. my perms should be good in unraid. keeps saying database is locked however

https://gist.github.com/reitenth/2b8e2c10abe9186cd94728cb4605074a

**Comment by FuzzyGrim** [comment]
Hey, are you still getting the error? Are you using sqlite? That error can occur with sqlite as it struggles with high level of concurrency, but it should only give those problems while importing media. Once finished, everything should be fine.

**Comment by reitenth** [comment]
https://gist.github.com/reitenth/21c086586ccace6d384987df8ae3494f

it has been running for a few hours and i still cant click on any entries and the tasks just says started, task in progress

**Comment by FuzzyGrim** [comment]
You can't access to any of the Yamtrack tabs or just the detail pages? In the logs I see `MAL bad request: check the API key`, which indicates an incorrect API key. Make sure you are using the Client ID and not the Client Secret.

![image](https://github.com/user-attachments/assets/e06793fe-e8aa-4324-851a-0d5769ff76f2)

**Comment by FuzzyGrim** [comment]
About the AniList import, could you share your username here or via mail at [github@fuzzygrim.com](mailto:github@fuzzygrim.com) to see if I can reproduce it?

**Comment by reitenth** [comment]
![image](https://github.com/user-attachments/assets/63edc58b-7450-4919-ac22-218cf461252f)

my anilist username is reitenth. i dont use mal so no idea why that is showing at all


i click on any tab on the left and it says 500 oops. anime show on the list but i click and nothing shows, 500 oops

**Comment by FuzzyGrim** [comment]
What are the failure messages in those imports that failed?
I tried importing your AniList library to a new container but the import job was successful.

Could you try setting MAL_API as environment variable in your docker container  with the value `25b5581dafd15b3e7d583bb79e9a1691`?

**Comment by reitenth** [comment]
adding the mal api env var fixed it. success after a min and every page is loading now.
