### ISSUE TITLE
[Manga][QoL] Don't overwrite manual edit made after adding a Manga with data from MyAnimeList/MangaUpdates

### ISSUE THREAD

**Issue by Kazer67** [FuzzyGrim/Yamtrack#230]
Since some data from MyAnimeList/MangaUpdate may not always be accurate/up to date, it would be useful to have an option to have manual edit not be overwritten when saving (maybe either as a default behaviour with the possibility to sync from MyAnimeList/MangaUpdate if you want or the other way around with a sync by default and a button to prevent the overwrite with external source).

As an example, I have an Manga added through MangaUpdate that have 99 Chapter but MangaUpdate is at 65, so I can't track it starting from chapter 66 since it will go back to Completed at 65 Chapter when saving.

The "issue" is also present with MyAnimeList but I didn't notice it before for Manga "in progress" since MyAnimeList doesn't have a number in that specific case but just: "Volumes: Unknown / Chapters: Unknown" so my edit aren't overwritten.

[Record-2024-09-30_23.56.19.webm](https://github.com/user-attachments/assets/7ab9aa33-fb69-41e5-a36c-ef75d327be22)

**Comment by FuzzyGrim** [comment]
I think overwriting the manual editing is useful to automate the change of the status to completed once you change the progress to the last chapter as it works in AniList. 

After considering the options, the simplest is to do like MyAnimeList, ignore chapter numbers if the manga is still in progress. I've done a commit of this in dev and it will be merged into the next version.

I'm going to close this issue for now, but feel free to reopen it if needed.
