### ISSUE TITLE
Feature: Recreate missing db tables on startup

### ISSUE THREAD

**Issue by Cwavs** [FuzzyGrim/Yamtrack#234]
Sometimes data corruption could lead to a scenario where some tables exist but not others. In such cases, I think it makes sense to check for and create tables if they're missing on start up, so that way a user doesn't have to recreate the entire database if only say one table is missing.

Currently is a table is missing the app throws an error and seems to just return error 500s until it is re-created manually.

**Comment by FuzzyGrim** [comment]
Currently on every start up it looks for new tables and automatically creates them if there are any. 

I'm not sure how the old tables are being deleted, can you reproduce the case of the missing tables?

**Comment by Cwavs** [comment]
It's not something that's happened to me (at least without my intervention), but I've had other sql lite dbs that I was only able to partly recover from a dead drive, where some tables were perfectly intact and others weren't and had to be dropped.

That is a rare occurrence though, so I'd understand if you didn't want to implement functionality for it.

**Comment by FuzzyGrim** [comment]
Yeah, I don't think i will implement something for that, that's what backups are for. Especially because tables are usually not independent of each other, but contain values that depend on other tables.
