### ISSUE TITLE
[Feature] Books!

### ISSUE THREAD

**Issue by kannthus** [FuzzyGrim/Yamtrack#235]
Heya, I was curious if there was any plans to add Books to the list of media that can be tracked. It would be incredibly helpful to have a single location to keep track of all of my media/entertainment, especially for us book worms.

Not sure if this helps any, but I believe other places use the google books API, this can be done via https://console.cloud.google.com/apis/dashboard and creating credentials with access to the Google Books API.

Y'all have a pretty cool thing going on here, can't wait to see what it'll become going forward. 😄

**Comment by FuzzyGrim** [comment]
Hey! That sounds like a fantastic idea, I’m adding it to my roadmap.

I appreciate the suggestion, I’ll definitely check that out. Thanks!

**Comment by Kazer67** [comment]
Using one of the various ISBN database for the information should take care of a lot of the books and also comics (for example: https://isbnsearch.org / https://isbndb.com etc)

**Comment by rodaN90** [comment]
Could also add "Audio Books" and "Podcasts".

Together with the normal "Books" every useful tracking is added I guess. :)

**Comment by FuzzyGrim** [comment]
Completed on https://github.com/FuzzyGrim/Yamtrack/commit/58006475bc84d8eaa8c787843701e1bb1b91a12c
