### ISSUE TITLE
Demo website error after v0.15

### ISSUE THREAD

**Issue by mtc-20** [FuzzyGrim/Yamtrack#259]
Tried logging into the [demo website](https://yamtrack.fuzzygrim.com/), but after logging in with the demo credebtials, faced a template rendering error. 

Browser: Firefox v131.0.1 (with an adblocker plugin)
OS: Ubuntu 22.04.5 LTS

PS. I also tried in privacy mode and  ran into same error.

Error screenshot:
![Screenshot from 2024-11-04 10-59-52](https://github.com/user-attachments/assets/a953ee19-86e4-4147-afc7-48d869fd8a4f)

**Comment by FuzzyGrim** [comment]
Thanks for reporting the issue, I just fixed it.
