### ISSUE TITLE
Mass import games with no images

### ISSUE THREAD

**Issue by R3laxAti0n** [FuzzyGrim/Yamtrack#272]
Hello, I’m having a weird issue but that might be normal behavior.
I tried to import a huge amount of games (150) but I didn’t add the image in the csv import. 
I got this bug : 
![image](https://github.com/user-attachments/assets/97ee855e-aa8a-45a8-9b5d-bac591e0d624)

So I did another import and added, by hands, all images links and deleted all the games from my library to import them again with links. 
Unfortunately I still have no images showing...
Is there anyway, is there a way to reload the metadata or will it charge over time ?

Thanks for the awesome software !

**Comment by FuzzyGrim** [comment]
Hey, thanks for reporting the error.

Previously it only created the metadata if a new media entry was created, I have changed it so that it updates the metadata on import. It is currently in the development branch and will be released tomorrow.

**Comment by R3laxAti0n** [comment]
Waouh ! Thank you so much for the quick fix !
Have a wonderful day !
