### ISSUE TITLE
importing csv without image url

### ISSUE THREAD

**Issue by reitenth** [FuzzyGrim/Yamtrack#280]
i can click the entry and it shows the poster, but in it does not show in the list. when i export from sites it does not ever give a tmdb poster url, is there someway to have a task generate them?
<img width="498" alt="image" src="https://github.com/user-attachments/assets/a214440d-939b-4d24-a752-3c43416d94c4">

**Comment by FuzzyGrim** [comment]
Currently it is not possible to regenerate the metadata, I will add a fix soon.
