### ISSUE TITLE
[Bug] Disable a media in settings does not disable it from the search bar

### ISSUE THREAD

**Issue by ndeleforge** [FuzzyGrim/Yamtrack#296]
Hello!
Version : 0.17.2

Settings : 
![Capture d’écran du 2024-12-22 12-12-33](https://github.com/user-attachments/assets/3627e480-6c32-43fc-90d5-779c234ac4e9)

Current behavior :
When I disable some media in my profile settings, they are gone from the menu as expected. However, I can still select the disabled media in the select input besides the search bar.

Expected behavior : 
I guess I should not be able to select a disabled media.

**Comment by FuzzyGrim** [comment]
Hi,

I have just added an option to hide the media types from the search bar
